# Generated by Django 5.1.3 on 2024-11-27 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='boleteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_concierto', models.DateTimeField(auto_created=True)),
                ('concierto', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('precio', models.BigIntegerField()),
            ],
        ),
    ]
